stages:
  prepare_data:
    cmd: python3 code/datasets/prepare_data.py
    deps:
      - code/datasets/prepare_data.py
      - data/raw/winequality-red.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train_model:
    cmd: python3 code/models/train.py
    deps:
      - code/models/train.py
      - data/processed/train.csv
      - data/processed/test.csv
    outs:
      - models/model.joblib
    metrics:
      - metrics/metrics.json